- .prettierrc
- package.json
- yarn.lock
- 매끄러운 협업을 위한 prettier 셋업
현재 적용된 prettier 옵션은 다음과 같습니다.
```
{
"singleQuote": true, // single 쿼테이션 사용 여부
"semi": true, // 세미콜론 사용 여부
"useTabs": false, // 탭 사용 여부
"tabWidth": 2, // 탭 너비 
"trailingComma": "all", // 여러 줄을 사용할 때, 후행 콤마 사용 방식
"printWidth": 80, //  줄 바꿈 할 폭 길이
"arrowParens": "avoid", // 화살표 함수 괄호 사용 방식
}
```
> chore: 협업을 위한 prettier 설치 및 설정

- src/api/admin.ts
- src/api/game.ts
- src/api/instance.ts
- 사용자용 api instance와 관리자용 api instance를 분리
> chore: 사용자용 api instance와 관리자용 api instance 분리

- .gitignore
- next.config.js
- src/api/auth.ts
- src/api/instance.ts
- src/app/login/page.tsx
- src/types/auth.ts
- src/types/game.ts
- 로그인 페이지 작성
- 각종 수정사항들(gitignore, 오타 수정, next.config.js 도메인 추가)
> [FEAT] Login 페이지 작성

- src/app/layout.tsx
> [DESIGN] root layout에 p-4 추가

- src/components/common/Game/GameLive.tsx
- src/components/common/Game/GameMain.tsx
- src/components/common/Game/GameScore.tsx
- src/components/common/Game/GameTeamLogo.tsx
- src/components/common/Game/GameTeamName.tsx
- src/components/detail/GameInfo.tsx
- src/types/game.ts
- GameInfo 컴포넌트 디자인 변경
|변경 전|변경 후|
|------|------|
|![image](https://github.com/hufs-sports-live/client/assets/87803596/fb55684e-f79d-4cd5-8811-a1bfe7f92410)|![image](https://github.com/hufs-sports-live/client/assets/87803596/2c762625-859e-45e7-af64-aab6a1c5414c)|
- GameScore - fontWeight 속성 추가로 기존 메인 페이지 게임 카드들도 semibold 글씨 굵기 반영됨
- 자세한 변경 사항은 커밋 내 코멘트 참조 바람!
> [DESIGN] 상세 페이지 GameInfo 디자인 변경

- .gitignore
- next.config.js
- package.json
- sentry.client.config.ts
- sentry.edge.config.ts
- sentry.server.config.ts
- src/api/admin.ts
- src/api/auth.ts
- src/api/game.ts
- src/api/team.ts
- src/app/_error.tsx
- src/app/admin/page.tsx
- src/app/detail/[id]/page.tsx
- src/app/layout.tsx
- src/app/login/page.tsx
- src/app/page.tsx
- src/components/detail/Comment.tsx
- src/components/detail/GameComments.tsx
- src/types/game.ts
- yarn.lock
- 댓글 블러 기능 버튼 추가
- 블러된 댓글은 회색처리, 삭제 버튼 사라짐
- 이외에 디자인 살짝 손 봄, 댓글 작성 기록도 수정함
- radixui/react-icons 미리 설치함
> [FEAT] 댓글 블러 기능 구현

- .github/workflows/sync.yml
- 올겐 main에 머지되면 vercel에 연결된 개인레포에 merge되는 GitHub action yml 작성
> feat: 개인 레포 merge yml파일 작성

- .github/workflows/sync.yml
> fix: 개인 레포 merge yml파일 수정

- .commitlintrc.json
- .husky/commit-msg
- .husky/pre-commit
- package.json
- yarn.lock
- #40 
- `husky` 설치
- `commitlint-cli`, `commitlint/config-conventional` 설치
- git commit 시 코드 컨벤션 및 커밋 메시지 검사
- 해당 프로젝트에서 커밋 컨벤션의 기초가 되는 규칙입니다.
https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional
- 커밋 타입은 [Angular Commit Rule](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#-commit-message-format)을 바탕으로 팀원과 논의하여 커스텀 했습니다.
- build: 외부 의존성 설치나 빌드 시스템에 영향을 주는 변경사항
- ci: CI 환경설정이나 스크립트에 변화가 있는 경우
- docs: 문서, 주석 관련
- feat: 새로운 기능 추가
- fix: 버그 픽스
- perf: 퍼포먼스를 향상시키는 변경사항
- refactor: 버그 픽스 또는 기능 추가에 해당하지 않는 코드 개선
- test: 테스트 관련 수정
- style: UI 변경사항
- chore: 그 외 자잘한 변경사항
> [BUILD]: husky & commitlint로 커밋 메시지 강제

- src/api/admin.ts
- src/api/auth.ts
- src/api/game.ts
- src/api/team.ts
- src/app/admin/page.tsx
- src/app/detail/[id]/modify/page.tsx
- src/app/detail/[id]/page.tsx
- src/app/page.tsx
- src/components/common/Game/GameLive.tsx
- src/components/detail/Comment.tsx
- src/components/detail/GameComments.tsx
- src/components/detail/GameInfo.tsx
- src/components/detail/GameTimeline.tsx
- src/components/detail/Record.tsx
- src/components/home/GameList/GameWithScore.tsx
- src/components/home/GameList/GameWithTimeStamp.tsx
- src/types/admin.ts
- src/types/auth.ts
- src/types/game.ts
- api 함수와 관련된 타입 네이밍 새로 정한 컨벤션에 따라 재작명
- 새로운 변경사항 적용(rebase)
> [CHORE] 타입 컨벤션에 따른 수정

- .prettierrc
- package.json
- src/app/admin/page.tsx
- src/app/detail/[id]/modify/page.tsx
- src/app/detail/[id]/page.tsx
- src/app/detail/[id]/status/page.tsx
- src/app/layout.tsx
- src/app/page.tsx
- src/components/common/Game/GameWrapper.tsx
- src/components/common/Game/Label.tsx
- src/components/common/Game/Score.tsx
- src/components/common/Game/Status.tsx
- src/components/common/Game/Team.tsx
- src/components/common/Input/Input.tsx
- src/components/common/Select/Select.tsx
- src/components/detail/CommentItem.tsx
- src/components/detail/CommentList.tsx
- src/components/detail/GameInfo.tsx
- src/components/detail/Record.tsx
- src/components/home/GameItem/index.tsx
- src/components/home/GameList/GameWithTimeStamp.tsx
- src/utils/core.ts
- yarn.lock
- #47
- prettier-plugin-tailwindcss 설치
- 이에 맞게 클래스명 순서 재정렬
- tailwind-merge, clsx 설치
- 두 라이브러리를 조합하여 클래스명 병합 유틸 함수 생성
- 아래와 같이 사용할 수 있음
```ts
export const $ = (...inputs: ClassValue[]) => {
return twMerge(clsx(inputs));
};
export default function Status({ className }: StatusProps) {
const { gameStatus } = useGameContext();
return <div className={$(className)}>{GAME_STATUS[gameStatus]}</div>;
}
```
- 클래스를 주입 받아 사용할 수 있는 컴포넌트에서 사용하면 될 것 같음
> [REFACTOR] Tailwindcss 사용성 향상

- .github/workflows/ci.yml
- build.sh
- #52 
- 루트 디렉토리에 build.sh 생성
- 해당 build.sh 실행하는 step ci.yml에 추가
- [GitHub Organization 프로젝트를 vercel 무료로 연동하기 (+git actions)](https://github.com/hufs-sports-live/client/pull/new/ci/add-shell)
> ci: 쉘스크립트 및 yml step 추가

- .github/workflows/ci.yml
- build.sh
- #54 
- 쉘스크립트 오타 수정
- ci.yml에 테스트 스텝 추가
- [GitHub Organization 프로젝트를 vercel 무료로 연동하기 (+git actions)](https://velog.io/@rmaomina/organization-vercel-hobby-deploy)
> Ci/쉘스크립트 오타 수정

- tailwind.config.ts
- #57 계승
- #57 과 동일
- x
- 충돌 병합 커밋으로 불필요한 커밋 때문에 다시 PR.
> [CHORE]: 컬러 팔레트 추가

- package.json
- src/api/league.ts
- src/components/common/Modal/index.tsx
- src/components/layout/Header.tsx
- tailwind.config.ts
- yarn.lock
- #70 
- 재사용 Modal 공통 컴포넌트 구현
- 햄버거 메뉴 사이드바 구현
- 사이드바 내 메뉴 링크 구현
- 사이드바 오픈/하이드 트렌지션 구현
- 리그 관련 api 작성
- [tailwindcss: data-[state:open]](https://tailwindcss.com/docs/hover-focus-and-other-states#data-attributes)
- [radix-ui: trigger](https://tailwindcss.com/docs/hover-focus-and-other-states#data-attributes)
- [tailwindcss: customizing keyframes](https://tailwindcss.com/docs/animation#customizing-your-theme)
- 사이드바 내 UI 확정 필요
> [FEAT]: 헤더 햄버거 메뉴 구현

- package.json
- src/api/league.ts
- src/app/layout.tsx
- src/components/common/Modal/index.tsx
- src/components/common/Sidebar/index.tsx
- src/components/layout/Header.tsx
- tailwind.config.ts
- yarn.lock
- #66 
- 헤더 기초 UI 작성
- 좌측 로고/타이틀 + 우측 햄버거메뉴 버튼
- 훕치치 로고 교체 필요
- 헤더 내 패딩 값 임의로 지정 -> 추후 수정 필요
> [STYLE]: 헤더 기초 UI 디자인

- src/api/match.ts
- src/app/match/[id]/page.tsx
- src/components/match/Video/index.tsx
- src/constants/videoSrc.ts
- src/queries/useMatchTimelineById/Fetcher.tsx
- src/queries/useMatchTimelineById/query.ts
- src/queries/useMatchVideoById/Fetcher.tsx
- src/queries/useMatchVideoById/query.ts
- src/types/match.ts
- #82
- getMatchVideoById api 함수 추가 및 관련 query, fetcher 생성
> [FEAT] Match VideoId 호출 및 화면에 띄어주기

- src/api/league.ts
- src/api/match.ts
- src/app/page.tsx
- src/components/common/Sidebar/index.tsx
- src/components/league/SportsList/index.tsx
- src/hooks/useQueryParams.ts
- src/queries/useSportsListByLeagueId/Fetcher.tsx
- src/queries/useSportsListByLeagueId/query.ts
- src/types/league.ts
- #90
- SportsList 컴포넌트 생성
- useQueryParams 함수 생성
> [FEAT] main sports categories 생성

- src/app/match/[id]/page.tsx
- src/components/common/MatchCard/pieces/Label.tsx
- src/components/common/MatchCard/pieces/Score.tsx
- src/components/common/MatchCard/pieces/Team.tsx
- src/components/match/Banner/index.tsx
- src/components/match/CheerTeam/index.tsx
- src/components/match/CommentForm/index.tsx
- src/queries/useMatchCommentById/Fetcher.tsx
- src/queries/useMatchCommentById/query.ts
- src/queries/useMatchList/query.ts
- src/types/match.ts
- 이슈 번호
- 임시 이미지를 추가하여 팀 정보가 없어도 화면이 다운되지 않도록 합니다.
> [FIX] 팀 정보 없을 시 화면이 다운되는 에러 해결

- src/app/login/page.tsx
- src/components/common/Icon/iconMap.ts
- src/queries/admin/useLeagueList/query.ts
- src/queries/useLogin/query.ts
- #97 
- 로그인 리팩토링, 누락된 아이콘 추가 등
- 누락된 CheckCircled 추가했습니다. 여기까지 머지해야 에러 없을거같아요!
> [REFACTOR]: login 리팩토링

- src/app/login/page.tsx
- src/queries/useLogin/query.ts
- 
- 로그인 pending, error 상태문구 추가
- 로그인 관련해서 사이드바 관리자 여부 확인도 함께 진행하려했는데 시간이 부족해서 우선 이 커밋만 올립니다!
> [STYLE]: 로그인 pending, error 상태 확인 문구 추가

- sentry.client.config.ts
- sentry.edge.config.ts
- sentry.server.config.ts
- src/app/layout.tsx
- src/types/ga/gtag.ts
- 이슈 번호
- google analytics 추가
- sentry dsn을 환경 변수로 저장
> [FEAT] google analytics 추가

- src/api/match.ts
- src/app/page.tsx
- src/components/match/CommentForm/index.tsx
- src/components/match/MatchList/index.tsx
- src/queries/useMatchList/Fetcher.tsx
- src/queries/useMatchList/query.ts
- #122
- 서버 문제로 인해 무한 스크롤을 잠시 제거합니다.
- 빈 값을 입력 시 댓글 등록 방지가 제대로 동작하지 않던 버그를 수정합니다.
> [FIX] 무한 스크롤 제거
